"""Shared primitives for mosaic and STOS grid refinement."""

from nornir_imageregistration.refine_shared.runtime_config import RefineRuntimeConfig, get_runtime_config
from nornir_imageregistration.refine_shared.anchor_smooth import (
    AnchorSmoothSettings,
    compute_locked_displacement_field,
    mesh_dims_from_records,
    should_use_anchor_smooth_mesh,
    smooth_peaks_from_locked_anchors,
)
from nornir_imageregistration.refine_shared.cell_validity import is_alignable_cell
from nornir_imageregistration.refine_shared.cell_roles import (
    DEFAULT_IDENTITY_ZNCC_MIN,
    FieldMode,
    RejectReason,
    Role,
    RoleClassificationResult,
    classify_field,
    classify_roles,
    exclude_reject_mesh_records,
    field_brand_identity_suspect_ids,
    unique_large_travel_raw_preserve_ids,
    coherent_discontinuity_raw_preserve_ids,
    DISC_FRONT_MIN_CELLS,
    DISC_FRONT_INLIER_COS,
    DISC_FRONT_COHERENCE_MIN,
    active_unique_field_is_hot,
    identity_zncc_min_threshold,
    masked_zncc,
)
from nornir_imageregistration.refine_shared.cell_history import (
    CellPassHistoryStore,
    write_cell_history_plots,
)
from nornir_imageregistration.refine_shared.source_content_cache import (
    SourceContentCache,
    crop_source_cell_std,
    crop_source_cell_stds_batched,
)
from nornir_imageregistration.refine_shared.cutoff import (
    filter_records_by_registration_weight,
    filter_alignment_records_by_weight,
    filter_weights_by_estimate_cutoff,
    estimate_registration_weight_cutoff,
)
from nornir_imageregistration.refine_shared.cell_measurement import (
    normalize_cell,
    measure_translation_cell,
    measure_translation_cells_batched,
)
from nornir_imageregistration.refine_shared.discontinuity import (
    discontinuity_travel_multiplier,
    per_record_max_travel,
    sharp_warps_enabled,
    tag_discontinuities,
)
from nornir_imageregistration.refine_shared.displacement_regularize import regularize_displacements
from nornir_imageregistration.refine_shared.finalize import (
    FinalizeCandidateState,
    FinalizeEvaluationResult,
    FinalizeSettings,
    evaluate_finalize_candidates,
    filter_records_for_mesh_inclusion,
    legacy_finalize_mask,
    unlock_stale_finalized,
    use_legacy_finalize_gate,
)
from nornir_imageregistration.refine_shared.pass_diagnostics import (
    PassDiagnosticRow,
    build_pass_diagnostic_rows,
    pass_diagnostics_enabled,
    write_pass_diagnostics,
)
from nornir_imageregistration.refine_shared.peak_ratio_gates import (
    PEAK_RATIO_EARLY,
    PEAK_RATIO_MIN,
    ambiguous_record_ids,
    exclude_ambiguous_mesh_records,
    finite_peak_ratio,
    is_ambiguous_peak,
    is_early_lock_ratio,
    soft_discontinuity_ids,
)
from nornir_imageregistration.refine_shared.phase_timer import RefinePhaseTimer, get_phase_timer
from nornir_imageregistration.refine_shared.failure_mode_stats import (
    identity_lock_mask,
    peak_direction_coherence,
    spatial_half_stats,
)
from nornir_imageregistration.refine_shared.coherent_residual import (
    COHERENCE_MIN,
    LOCK_FRAC_TRIGGER,
    MIN_MESH_ABS_AFTER_RESIDUAL,
    MIN_MESH_FRAC_AFTER_RESIDUAL,
    MIN_UNIQUE_PEAKS,
    CoherentResidualDiagnosis,
    CoherentResidualTranslation,
    diagnose_coherent_residual_translation,
    estimate_coherent_residual_translation,
    estimate_global_fov_residual_translation,
    should_attempt_global_fov_recovery,
    should_preserve_post_residual_transform,
)
from nornir_imageregistration.refine_shared.progress import (
    RefineGridProgressReporter,
    count_initial_grid_points,
    publish_stos_refine_files_progress,
)

__all__ = [
    'RefineRuntimeConfig',
    'get_runtime_config',
    'AnchorSmoothSettings',
    'compute_locked_displacement_field',
    'mesh_dims_from_records',
    'should_use_anchor_smooth_mesh',
    'smooth_peaks_from_locked_anchors',
    'is_alignable_cell',
    'DEFAULT_IDENTITY_ZNCC_MIN',
    'FieldMode',
    'RejectReason',
    'Role',
    'RoleClassificationResult',
    'classify_field',
    'classify_roles',
    'exclude_reject_mesh_records',
    'field_brand_identity_suspect_ids',
    'unique_large_travel_raw_preserve_ids',
    'coherent_discontinuity_raw_preserve_ids',
    'DISC_FRONT_MIN_CELLS',
    'DISC_FRONT_INLIER_COS',
    'DISC_FRONT_COHERENCE_MIN',
    'active_unique_field_is_hot',
    'identity_zncc_min_threshold',
    'masked_zncc',
    'CellPassHistoryStore',
    'write_cell_history_plots',
    'SourceContentCache',
    'crop_source_cell_std',
    'crop_source_cell_stds_batched',
    'filter_records_by_registration_weight',
    'filter_alignment_records_by_weight',
    'filter_weights_by_estimate_cutoff',
    'estimate_registration_weight_cutoff',
    'normalize_cell',
    'measure_translation_cell',
    'measure_translation_cells_batched',
    'discontinuity_travel_multiplier',
    'per_record_max_travel',
    'sharp_warps_enabled',
    'tag_discontinuities',
    'regularize_displacements',
    'FinalizeCandidateState',
    'FinalizeEvaluationResult',
    'FinalizeSettings',
    'evaluate_finalize_candidates',
    'filter_records_for_mesh_inclusion',
    'legacy_finalize_mask',
    'unlock_stale_finalized',
    'use_legacy_finalize_gate',
    'PassDiagnosticRow',
    'build_pass_diagnostic_rows',
    'pass_diagnostics_enabled',
    'write_pass_diagnostics',
    'PEAK_RATIO_EARLY',
    'PEAK_RATIO_MIN',
    'ambiguous_record_ids',
    'exclude_ambiguous_mesh_records',
    'finite_peak_ratio',
    'is_ambiguous_peak',
    'is_early_lock_ratio',
    'soft_discontinuity_ids',
    'RefinePhaseTimer',
    'get_phase_timer',
    'identity_lock_mask',
    'peak_direction_coherence',
    'spatial_half_stats',
    'COHERENCE_MIN',
    'LOCK_FRAC_TRIGGER',
    'MIN_MESH_ABS_AFTER_RESIDUAL',
    'MIN_MESH_FRAC_AFTER_RESIDUAL',
    'MIN_UNIQUE_PEAKS',
    'CoherentResidualDiagnosis',
    'CoherentResidualTranslation',
    'diagnose_coherent_residual_translation',
    'estimate_coherent_residual_translation',
    'estimate_global_fov_residual_translation',
    'should_attempt_global_fov_recovery',
    'should_preserve_post_residual_transform',
    'RefineGridProgressReporter',
    'count_initial_grid_points',
    'publish_stos_refine_files_progress',
]
